### ISSUE TITLE
dcconvertencoding and dcwindows.pas are necesary to compile usysinfo.pas

### ISSUE THREAD

**Issue by federico32** [r3code/lazarus-exception-logger#10]
Hi,
The dcconvertencoding.pas and dcwindows.pas are necesary to compile usysinfo.pas

Thank you

**Comment by r3code** [comment]
@federico32 Why didn't you make a pull request?

**Comment by federico32** [comment]
No. We did Download Proyect
![image](https://user-images.githubusercontent.com/7966700/63171393-ddd1c500-c011-11e9-8026-0a3b67236b3a.png)

and if you search this file on the proyect; were not found.
![image](https://user-images.githubusercontent.com/7966700/63171607-428d1f80-c012-11e9-9754-1dd9b8b245f8.png)

**Comment by federico32** [comment]
I made a class that inherits from TExceptionLogger to add the ability to not display the exception dialog but if you save the log in a file, be able to add the date to the file name and execute an event controlled by the application when the exception is raised.
To be able to use it, you must change it in the UExceptionLogger unit TExceptionLogger = class (TComponent)
from Private to Protected
I enclose an example of use.

If you find these extra features useful, add them to the new version.

[LXexcept.zip](https://github.com/r3code/lazarus-exception-logger/files/3510021/LXexcept.zip)

**Comment by federico32** [comment]
Sorry, I Close it for error
