### ISSUE TITLE
Not compiling on Linux

### ISSUE THREAD

**Issue by circular17** [r3code/lazarus-exception-logger#13]
On line 278 of lelDCConvertEncoding.pas, I suppose the include filename need the prefix lel:
`{$I dcconvertencoding.inc} `

On line 30 of lelDCWindows, it complains it cannot find the Windows unit.

**Comment by r3code** [comment]
@circular17 can you try to fix it?
I suggest removing `lel*` units from the Package Project, then it will regenerate ExceptionLogger.pas
After that try to run Examples.

**Comment by circular17** [comment]
Removing leldcwindows.pas from the package solved the problem.

**Comment by circular17** [comment]
Oops maybe not close the issue now.

**Comment by r3code** [comment]
> 
> 
> Removing leldcwindows.pas from the package solved the problem.

Did you remove it from the lpk file?

**Comment by circular17** [comment]
Yep

**Comment by r3code** [comment]
> 
> 
> Yep

So now it's working? Can we close the issue?

**Comment by circular17** [comment]
Yes it works fine now.
