### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by lainz** [r3code/lazarus-exception-logger#6]
Hi,

In a project we're using the original lazarus-exception-logger and we want to change to your improved version.

This works properly on mac? The one that installed the lazarus-exception-logger on the project had to make some changes (ifdefs) to work on mac. Is this fixed?

Thanks.

**Comment by r3code** [comment]
@lainz I have no ability to test it on Mac. I work primarily with Windows and Linux. 
You can test it yourself with Mac just run demo or make a small test app raising your errors without handling them with try\except and try it.

Please report your results here.
